### PR TITLE
streaming duration is not required field, when it's 0 that means as soon as possible.

### PR DESCRIPTION
**Pull request by zml1206**
streaming duration非必须，默认为0，代表as soon as possible

### CODE REVIEW

**Comment by allwefantasy** [comment]
It seems that the feature `as soon as possible` is only available in spark 2.3.x.  Can you try to test it in spark 2.2.x? 

You can use `org.apache.spark.SparkCoreVersion` to get the version where MLSQL runs on. If it does not supports 2.2.x, check the version and throws an exception if need.

**Comment by allwefantasy** [comment]
Also I do not think this is a bug because people can set the duration to 0 explicitly.

**Comment by zml1206** [comment]
I tested  and found  it supports 2.2.X, 2.3.X and 2.4.X

**Comment by allwefantasy** [comment]
We will close this issue if you have any other question please reopen it.

**Pull request closed without merging**
