### PR TITLE
Add load syntax validation

### PR DESCRIPTION
**Pull request by anan0120**
for example:
load jdbc.`db_1.test`
where directQuery='''
select id FROM awh_test2 where
''' as out;

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

### CODE REVIEW

**Comment by allwefantasy** [comment]
Thanks for your issue. But there are some optimizations we can do.

1.  There is no need to analyze the load statement again in `LoadGrammarAdaptor` since we have provided `analyze` function in LoadAdaptor. You can then get `directQuery` from LoadStatement and validate the syntax.
2. You can also rewrite `SelectGrammarAdaptor` according to the way I mentioned.

**Comment by anan0120** [comment]
修改为直接使用LoadAdaptor中提供了analyze函数，目前这个验证有点局限，仅仅只验证了 jdbc directQuery的语法验证，实例如下：

```sql
 load jdbc.`db_1.test` 
where directQuery='''
select * FROM awh_test2 where
''' as out; 
```

```scala


GrammarProcessListener类修改=======
  override def exitSql(ctx: SqlContext): Unit = {
    ctx.getChild(0).getText.toLowerCase() match {
      case "select" =>
        new SelectGrammarAdaptor(this).parse(ctx)
      case "load" =>
        val loadStatement = new LoadAdaptor(this).analyze(ctx)
        if(loadStatement.format.toUpperCase == "JDBC" && loadStatement.option.getOrElse("directQuery","") != ""){
          val repository = new SchemaRepository(loadStatement.option.getOrElse("dbType",JdbcConstants.MYSQL))
          val directQuery = loadStatement.option.getOrElse("directQuery","")
          try {
            repository.console(directQuery)
          } catch {
            case e: Exception => {throw new RuntimeException("SQL syntax error, please check:"+directQuery)}
          }
        }
      case _ =>
    }
  }
```


我也考虑了你提议的插件用法：

```sql
select crawler_http("http://127.0.0.1:9003/run/script","POST",map("owner","wow","sql","select 1 as a as output;","executeMode","echo")) as c as output;
```

如果sql语句是多个的话，我想验证语法、表或字段是否存在的，是不是也需要再对语句进行解析，就类似你关键字适配器？还是怎么做

**Comment by allwefantasy** [comment]
你还是需要些一个LoadGrammarAdaptor,然后代码都放在那里面。

**Comment by anan0120** [comment]
好的，明白你的意思了，我再修改下

**Comment by anan0120** [comment]
已修改 LoadGrammarAdaptor，共用LoadAdaptor.analyze解析避免多处解析，
非常感谢作者细心指导！

  override def parse(ctx: DSLSQLParser.SqlContext): Unit = {
    val loadStatement = new LoadAdaptor(grammarProcessListener).analyze(ctx)
    if(loadStatement.format.toUpperCase == "JDBC" && loadStatement.option.getOrElse("directQuery","") != ""){
      val repository = new SchemaRepository(loadStatement.option.getOrElse("dbType",JdbcConstants.MYSQL))
      val directQuery = loadStatement.option.getOrElse("directQuery","")
      try {
        repository.console(directQuery)
      } catch {
        case e: Exception => {throw new RuntimeException("SQL syntax error, please check:"+directQuery)}
      }
    }
  }

**Pull request closed without merging**
